HashSyntax:
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - hash_rockets

CaseIndentation:
  SupportedStyles:
    - case
    - end
  IndentOneStep: true

StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

SignalException:
  EnforcedStyle: only_raise

ConstantName:
  Enabled: false

IfUnlessModifier:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

AsciiComments:
  Enabled: false

Proc:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

Encoding:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

FileName:
  Enabled: false

ClassLength:
  Max: 200

MethodLength:
  Max: 30

CyclomaticComplexity:
  Max: 7

LineLength:
  Enabled: false

