HashSyntax:
  EnforcedStyle: ruby19

StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

SignalException:
  EnforcedStyle: only_raise

ConstantName:
  Enabled: false

IfUnlessModifier:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

AsciiComments:
  Enabled: false

Proc:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

Encoding:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

FileName:
  Enabled: false

ClassLength:
  Max: 200

MethodLength:
  Max: 18

LineLength:
  Enabled: false

